export default function Terms() {
  return (
    <div className="page">
      <div className="container">
        <div className="static-page">

          <h2>Terms of Service</h2>
          <p className="static-date">Last updated: January 2026</p>

          <h3>Use of Service</h3>
          <p>
            By using AI Project Generator, you agree to use the generated
            content for educational and reference purposes only. You must
            not use this service for any illegal or harmful activities.
          </p>

          <h3>Generated Content</h3>
          <p>
            The projects and code generated by this tool are for reference
            only. Always review, test, and verify before using in any
            production environment. We are not responsible for errors in
            generated content.
          </p>

          <h3>Availability</h3>
          <p>
            We do not guarantee uninterrupted access to the service. The
            service may be down for maintenance or due to third-party
            API limitations.
          </p>

          <h3>Limitation of Liability</h3>
          <p>
            We are not liable for any damages arising from the use of
            this service or the generated content.
          </p>

        </div>
      </div>
    </div>
  );
}