export default function Disclaimer() {
  return (
    <div className="page">
      <div className="container">
        <div className="static-page">
          <h2>Disclaimer</h2>
          <h3>Educational Purpose Only</h3>
          <p>All projects and code generated by this tool are strictly for educational and reference purposes. They should not be submitted as original academic work without proper review and modification.</p>
          <h3>Accuracy</h3>
          <p>AI-generated content may contain errors, outdated information, or incomplete implementations. Always verify with reliable sources before using.</p>
          <h3>No Warranty</h3>
          <p>This service is provided as-is without any warranty of any kind. We make no guarantees about the accuracy or completeness of the generated content.</p>
          <h3>Academic Integrity</h3>
          <p>Users are responsible for ensuring their use of this tool complies with their institution's academic integrity policies.</p>
        </div>
      </div>
    </div>
  );
}